### ISSUE TITLE
How to get the  "resource name" while using the Cloudtrail processing library

### ISSUE THREAD

**Issue by SyCode7** [aws/aws-cloudtrail-processing-library#10]
In the screenshot of event history (taken from the CloudTrail web console) , the name of the bucket affected by a change is reflected under the column: `Resource name` .  How can I retrieve this same value using the  `aws-cloudtrail-processing-library` . The library returns the name of the bucket where CloudTrail saves the log files and not the affected bucket. Also, even after downloading the logs from the bucket,   I do not see this information.

![cloudtrail_web_console](https://user-images.githubusercontent.com/6909640/48275499-e9baa600-e445-11e8-9392-4e349d1d588a.PNG)

Do I need to use the the `LookupAttribute` as stated in the documentation for [CloudTrail API ](https://docs.aws.amazon.com/awscloudtrail/latest/APIReference/API_LookupAttribute.html) ?

**Comment by jeffmcr** [comment]
The ability to get the Resource name for this API using the CloudTrail Processing Library is not currently supported.  We will consider this feature in a future version of CPL.

**Comment by SyCode7** [comment]
Okay, as an alternative,is all the information available in the specified cloudtrail bucket as specified in this [documentation](https://docs.aws.amazon.com/awscloudtrail/latest/userguide/cloudtrail-event-reference.html) ?

**Comment by jeffmcr** [comment]
Yes, the information is available from the requestParameters or responseElements in the events which are delivered to your s3 bucket.

**Comment by SyCode7** [comment]
Thank you very much! Will close the issue now.

**Comment by ranjiniganeshan** [comment]
Request parameters has the arn number not the resource name. Please advise.

**Comment by jeffmcr** [comment]
If you are attempting to get the last segment of the ARN, which is the resource-id or resource-type depending on service context, then CPL does not parse out individual segments of an ARN. You would have to parse it manually from the full ARN returned by CPL. 

Here is the public documentation for ARN formats: https://docs.aws.amazon.com/general/latest/gr/aws-arns-and-namespaces.html
