### ISSUE TITLE
DefaultEventsProcessor is always added with no way to remove

### ISSUE THREAD

**Issue by kzgrey** [aws/aws-cloudtrail-processing-library#11]
The following line block of code will result in aws-cloudtrail-processing-library spamming the log output with event names every time an event is processed:

`    Builder factory = new Builder(this, configuration_).withExceptionHandler(this);
    cloudTrailExecutor_ = factory.build();`

I believe the root cause is that the DefaultEventsProcessor is always registered for callbacks irrespective of whether or not an EventProcessor is defined.

https://github.com/aws/aws-cloudtrail-processing-library/blob/master/src/main/java/com/amazonaws/services/cloudtrail/processinglibrary/impl/DefaultEventsProcessor.java#L34

**Comment by simongjh** [comment]
kzgrey, the default `EventProcessor` is registered when no custom `EventProcessor` is provided. To get rid of the logging in the `DefaultEventProcessor` you can create a custom no-op `EventProcessor`, and add it to the `Builder`.
