### ISSUE TITLE
IllegalArgumentException: Invalid UUID string

### ISSUE THREAD

**Issue by johnolos** [aws/aws-cloudtrail-processing-library#3]
Hi! I'm currently trying to use the DefaultEventSerializer.

In the AbstractEventSerializer:
Line 495-496 are causing an IllegalArgumentException:
private UUID convertToUUID(String str) {
    return UUID.fromString(str);
}

Context:
While I am processing CloudTrail logs; sometimes (maybe like 1-2 events every hour) an event has an "requestID" value which isn't a proper UUID, or so java complains.

Line 157-158 are the lines leading up to the use of that function.
158: eventData.add(key, this.convertToUUID(this.jsonParser.nextTextValue()));

Since this value isn't of any significance to me, it isn't any real issue, but the exception is however present when used in production.

**Comment by simongjh** [comment]
When CloudTrail Processing Library launched, all requestIDs in CloudTrail logs were UUIDs. However DynamoDB uses a different format, so CloudTrail Processing Library needs to change to make requestID a String. We will apply that fix after doing appropriate testing. We apologize for not making that change before DynamoDB added CloudTrail support.

**Comment by johnolos** [comment]
Not a problem and thanks for context of the issue.

Do you have an estimate of when you will be able to get to this?

**Comment by simongjh** [comment]
The code has been updated to parse RequestID as String instead of UUID. 
Maven repository is updated too.

**Comment by joe96814** [comment]
Shouldn't we have bumped the library version number with this update?

**Comment by simongjh** [comment]
We did not bump up the version. We will soon (in a few days) release another change to update the library with AWS Java SDK 1.10 and will dump up the version to 1.0.1
