### ISSUE TITLE
The artifacts deployed to Maven are fat JARs (50MB+)

### ISSUE THREAD

**Issue by grnadav** [aws/aws-cloudtrail-processing-library#6]
The artifacts deployed to [Maven repository com](https://mvnrepository.com/artifact/com.amazonaws/aws-cloudtrail-processing-library) are fat JARs , 50MB+, instead of ~90kb.

This is not only a size issue, but inside the JARs are complete versions of all the dependencies in the tree, such as Jackson (old one), a version that conflict with my project's version (newer).
These bundled dependencies cannot be excluded by a pom's exclusion, as they are not a dependency once they are baked into the JAR.

At this point the only workaround for me is to compile on my own and deploy to a private maven repo.

**Comment by simongjh** [comment]
Thanks for bringing this concern to us, we will address this issue in our upcoming releases.

**Comment by simongjh** [comment]
Should be fixed in the latest 1.1.0 release, let us know if you have any further question.

https://mvnrepository.com/artifact/com.amazonaws/aws-cloudtrail-processing-library/1.1.0
