### ISSUE TITLE
Release of 1.1.1 does not include the content stated in the release notes

### ISSUE THREAD

**Issue by grnadav** [aws/aws-cloudtrail-processing-library#7]
Hello

I tried to figure out what was the [diff. between 1.1.0 and 1.1.1 ](https://github.com/aws/aws-cloudtrail-processing-library/commit/11cd7d0bb3305f66b05569aff6b107959ccf5099) to better understand the release notes of 1.1.1, and found that no code was changed/added, nor any dependencies were updated, only minor docs change.

Were PRs/commits not pushed?

**Comment by mingma7** [comment]
Hi,

Thanks for pointing it out. The commits were not pushed properly in 1.1.1. We will push the commits in 1.1.2.  Apologize for any inconvenience it may cause.

**Comment by grnadav** [comment]
@mingma7 Thanks for the reply. I've been waiting for it for 3 months now. Is this project still active within AWS?

**Comment by mingma7** [comment]
Yes, it is. We are sorry about the late reply.

**Comment by mingma7** [comment]
We have released 1.1.2 today. Here is the [diff between 1.1.1 and 1.1.2](https://github.com/aws/aws-cloudtrail-processing-library/commit/e32a5270c1de75cf9d019530cfc29fa99b8599f9). Please feel free to let us know if you have any question.
