### ISSUE TITLE
How can I feed a property file to CloudTrailProcessingLibrary and use data from that property file

### ISSUE THREAD

**Issue by b2bking** [aws/aws-cloudtrail-processing-library#8]

**Comment by mingma7** [comment]
Hi,

Thanks for reaching out. 
For your reference, we have provided a sample application under aws-cloudtrail-processing-library/src/sample/.

In the file awscloudtrailprocessinglibrary.properties, you can specify your AWS configurations. And SampleApp.java has the example of using this property file. 

Please let us know if you have any question. Feel free to reopen the issue.
